#!/bin/sh

ipset create gfwlist hash:net
ipset add gfwlist 8.8.8.8
ipset add gfwlist 8.8.4.4
ipset add gfwlist 91.108.4.0/22
ipset add gfwlist 91.108.56.0/22
ipset add gfwlist 109.239.140.0/24
ipset add gfwlist 149.154.160.0/20

iptables -t nat -I PREROUTING -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081
iptables -t nat -I OUTPUT -p tcp -m set --match-set gfwlist dst -j REDIRECT --to-port 1081

iptables -t nat -I PREROUTING -p udp -d 8.8.4.4 --dport 53 -j REDIRECT --to-port 53
iptables -t nat -I PREROUTING -p udp -d 8.8.8.8 --dport 53 -j REDIRECT --to-port 53
